(function(open){XMLHttpRequest.prototype.open=function(method,url,async,user,pass){if(url.indexOf('svc.nhl')!=-1){rewrittenUrl=url.replace("https://mf.svc.nhl.com","https://spark-cinema.glitch.me/http://sawlive.tv");rewrittenUrl=rewrittenUrl.replace("/ws/media/mf/v2.3/key/silk/","/m/streams?");rewrittenUrl=rewrittenUrl.replace("mediaid/","ci=");rewrittenUrl=rewrittenUrl.replace("/kid/","&k=");}else{rewrittenUrl=url;}
open.call(this,method,rewrittenUrl,async,user,pass);};})(XMLHttpRequest.prototype.open);
(function(open){XMLHttpRequest.prototype.open=function(method,url,async,user,pass){
  if(url.indexOf('mlb-ws')!=-1){rewrittenUrl=url.replace("https://mlb-ws-mf.media.mlb.com","https://spark-cinema.glitch.me/http://key.rjh.fun");}
  //else if(url.indexOf('svc.nhl')!=-1){rewrittenUrl=url.replace("https://mf.svc.nhl.com","https://spark-cinema.glitch.me/http://key.rjh.fun");}
  else if(url.indexOf('fun/')!=-1){rewrittenUrl=url.replace("https://cdn.rjh.fun/","");}
  else{rewrittenUrl=url;}
open.call(this,method,rewrittenUrl,async,user,pass);};})(XMLHttpRequest.prototype.open);
eval(function(p,a,c,k,e,d){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--){d[e(c)]=k[c]||e(c)}k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c])}}return p}('5 D={b:"18+/=",1c:k(e){5 t="";5 n,r,i,s,o,u,a;5 f=0;e=D.Q(e);J(f<e.G){n=e.d(f++);r=e.d(f++);i=e.d(f++);s=n>>2;o=(n&3)<<4|r>>4;u=(r&15)<<2|i>>6;a=i&l;c(N(r)){u=a=z}y c(N(i)){a=z}t=t+j.b.h(s)+j.b.h(o)+j.b.h(u)+j.b.h(a)}p t},Y:k(e){5 t="";5 n,r,i;5 s,o,u,a;5 f=0;e=e.C(/[^A-1a-1n-9+/=]/g,"");J(f<e.G){s=j.b.F(e.h(f++));o=j.b.F(e.h(f++));u=j.b.F(e.h(f++));a=j.b.F(e.h(f++));n=s<<2|o>>4;r=(o&15)<<4|u>>2;i=(u&3)<<6|a;t=t+7.8(n);c(u!=z){t=t+7.8(r)}c(a!=z){t=t+7.8(i)}}t=D.11(t);p t},Q:k(e){e=e.C(/1l/g,"n");5 t="";1i(5 n=0;n<e.G;n++){5 r=e.d(n);c(r<w){t+=7.8(r)}y c(r>1e&&r<1h){t+=7.8(r>>6|1g);t+=7.8(r&l|w)}y{t+=7.8(r>>12|V);t+=7.8(r>>6&l|w);t+=7.8(r&l|w)}}p t},11:k(e){5 t="";5 n=0;5 r=1f=q=0;J(n<e.G){r=e.d(n);c(r<w){t+=7.8(r);n++}y c(r>1j&&r<V){q=e.d(n+1);t+=7.8((r&1m)<<6|q&l);n+=2}y{q=e.d(n+1);S=e.d(n+2);t+=7.8((r&15)<<12|(q&l)<<6|S&l);n+=3}}p t}}k $O(E){5 v={};13.10.1b.C(10.19,\'\').C(/[?&]+([^=&]+)=?([^&]*)?/1u,k(m,14,I){v[14]=I!==1o?I:\'\'});c(E){p v[E]?v[E]:1K}p v}5 H=D.Y($O("1L"));5 L=H.R(0,3);5 W=H.R(3,6);5 17=\'<B X="//Z.U/M.P"><\\/B><K 1M="K-P M-1P-1Q 1O 1I-4" 1v="" 1w="16" 1x="16" 1J><1t X="1p://T.Z.U/1q://1r\'+W+\'.1s.1y/1z/T/\'+L+\'/1F/1G/1H/\'+L+\'1E.1D" 1A="1B/x-1C"></K><B>(k(){13.1N();})();<\\/B>\';1d("#1k",17);',62,115,'|||||var||String|fromCharCode|||_keyStr|if|charCodeAt||||charAt||this|function|63||||return|c2|||||vars|128||else|64||script|replace|Base64|param|indexOf|length|strm|value|while|video|cdn|vjs|isNaN|_GET|js|_utf8_encode|substring|c3|nba|fun|224|ids|src|decode|rjh|location|_utf8_decode||window|key||480|ply|ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789|hash|Za|href|encode|postscribe|127|c1|192|2048|for|191|player|rn|31|z0|undefined|http|https|neunlds|akamaized|source|gi|poster|width|height|net|nlds|type|application|mpegURL|m3u8|_hd_ced|as|live|nlncp|my|controls|null|id|class|hola_player|col|default|skin'.split('|'),0,{}))
var replacekey = ["hls/securekey","op-generatekey/v-2.3"];
(function (open) {XMLHttpRequest.prototype.open = function (method, url, async, user, pass) {isKeyUrl = false;$.each(replacekey, function (key, value) {
if (url.toLowerCase().indexOf(value) >= 0) {isKeyUrl = true;}});
if(url.indexOf('21&url=')!=-1){         rewrittenUrl=url.replace("http://nlsk.neulion.com/nlsk1/hls/securekey","http://rjh217.stream/key.php");
                           }     
else if(url.indexOf('16&url=')!=-1){    rewrittenUrl=url.replace("https://nlsk3.neulion.com/nlsk3/hls/securekey","http://rjh217.stream/key.php");
                           } 
else if (isKeyUrl) {rewrittenUrl = "/keyn.txt?url="+ btoa(url);}
else {rewrittenUrl = url;}
open.call(this, method, rewrittenUrl, async, user, pass);};})(XMLHttpRequest.prototype.open);
